### PR TITLE
Remove recursive calling when fetching remote attributes.

### PR DESCRIPTION
**Pull request by h2zero**
Removes looping on recursive calls to retrieve(attribute) when the attribute UUID is not found and conversions attempted.

### CODE REVIEW

**Comment by DTTerastar** [comment]
This has massively fixed my uptimes so far!

**Comment by h2zero** [comment]
Great, I'll issue a release tomorrow if there are no further issues.

**Comment by DTTerastar** [comment]
> Great, I'll issue a release tomorrow if there are no further issues.

Are you going to do this still?

**Comment by h2zero** [comment]
Yes, it should be done in about an hour.

**Comment by h2zero** [comment]
The watchdog issues I'm unsure of, maybe you need to add a short delay or yield somewhere in your "BLE scan" task.

**Pull request merged**
