### PR TITLE
Add 'NimBLEClient::getPeerAddrType()'

### PR DESCRIPTION
**Pull request by wakwak-koba**
It is a case proposed in the following issue.
https://github.com/h2zero/NimBLE-Arduino/issues/98

### CODE REVIEW

**Comment by h2zero** [comment]
Can we change the naming to peerAddrType? It's a bit more typing but much clearer as to what the type means. 

The variable would then be m_peerAddrType and the method getPeerAddrType().

**Comment by wakwak-koba** [comment]
I don't care about this, so you can do what you want !

**Comment by h2zero** [comment]
Thank you for the update, looks good!

> I don't care about this, so you can do what you want !

Not sure of your meaning here, seems as though you're angry? Maybe a translation issue?

**Comment by wakwak-koba** [comment]
Maybe I should have used 'mind' instead of 'care' ...
I'm sorry in bad English

**Comment by h2zero** [comment]
@wakwak-koba No worries, I thought that may have been the case. Just wanted to check that I didn't upset you somehow.

As for this PR I have created a different one #104 that I think will be more generic. As well I have created a branch, feature/client-set-address to accompany it. These together should provide the functionality you requested in #98.

**Comment by wakwak-koba** [comment]
I saw #104, I think it's very cool !
Then, isn't it necessary to review the arguments of BLEClient::connect()?

`
    bool                                        connect(const NimBLEAddress &address, uint8_t type = BLE_ADDR_PUBLIC,
                                                        bool refreshServices = true);
`

Since it contains `type` in `NimBLEAddress`, I think it will cause confusion if it exists in the argument of `connect`.
Should `type` be excluded from arguments?

`
    bool                                        connect(const NimBLEAddress &address, bool refreshServices = true);
`

**Comment by h2zero** [comment]
The type has been removed from connect in the PR #106 which also incorporates the other parts of your request.

**Comment by h2zero** [comment]
I merged the other one, is there any need to keep this open?

**Comment by wakwak-koba** [comment]
This issue has been resolved in PR #106 and PR #104

**Pull request closed without merging**
