### PR TITLE
Define scanCompleteCB with using std::function

### PR DESCRIPTION
**Pull request by asukiaaa**
I want to use bind for scanCompleteCB like this.
```cpp
class Controller {
  void startScan() {
    scanning = true;
    auto pScan = NimBLEDevice::getScan();
    pScan->setAdvertisedDeviceCallbacks(advDeviceCBs);
    pScan->setInterval(45);
    pScan->setWindow(15);
    Serial.println("Start scan");
    // pScan->start(scanTime, scanEndedCB);
    pScan->start(scanTime,
                 std::bind(&Core::scanEndedCB, this, std::placeholders::_1)); // <<<<<<<<<< ======== Here
  }

  void scanEndedCB(NimBLEScanResults results) {
    Serial.println("Scan Ended");
    scanning = false;
  }
};
```

Related issue: https://github.com/h2zero/NimBLE-Arduino/issues/342

### CODE REVIEW

**Comment by h2zero** [comment]
Sorry for the delay. 

This is a good idea but we have a problem. 

This will break the API for users that do not provide the `is_continue` parameter when they provide a callback that does not use  std::bind (such as the examples). In this scenario the callback argument is converted to a `bool(true)` by the compiler and results in calling the wrong `start()` method, and the callback is not called.

In order to support this correctly another solution is needed. If we are going to break the API, I think the best way would be to have a `setScanEndCallback` method or a callback class added to `NimBLEScan` and remove the function parameter from the start calls. This would also require renaming the `start()` method to support the blocking and non-blocking calls with different naming.

I'm open to other suggestions, this is just my first thoughts.

Note: merging this will need to wait until the other breaking changes I have in mind are implemented with the upcoming 2.0 releases.

**Comment by asukiaaa** [comment]
Thank you for the response.
I understand that this change breaks current code.

> have a setScanEndCallback method or a callback class added to NimBLEScan

I agree passing a class instance for a function because we can support additional callback easily.

> I have in mind are implemented with the upcoming 2.0 releases.

I see, thanks.

**Comment by h2zero** [comment]
@asukiaaa Please take a look at #389, it is part of a few breaking changes I have planned for a version 2 release and should suit your needs.

**Comment by asukiaaa** [comment]
Thank you for updating but it seems renaming m_pAdvertisedDeviceCallbacks to m_pScanCallbacks and reuse it as m_scanCompleteCB.
Is it possible to distinguish the timing of finding some device and finishing scanning?

**Comment by h2zero** [comment]
Sorry, I need to update an examples to make it clearer. The advertised device callback class has been replaced with the scan callback class which contains the virtual function `onResult` and `onScanEnd` that you can define for your needs.

**Comment by asukiaaa** [comment]
Thank you for the explanation.
I could use the updated NimBLE without using global functions and variables.
https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32/commit/57e50c181ff621cfd5c6521d0ea36bd6ab32c68d

**Comment by h2zero** [comment]
You got it 😄

**Comment by asukiaaa** [comment]
This request is satisfied by onScanEnd callback on https://github.com/h2zero/NimBLE-Arduino/pull/389.
Thank you.

**Pull request closed without merging**
