### PR TITLE
No auto descriptors (includes PR #56 that in turn in includes PR #40)

### PR DESCRIPTION
**Pull request by Jeroen88**
With this PR descriptors for a characteristic are only retrieved from the peripheral when the central asks for that characteristic by calling `getDescriptor(... uuid ...)`. This saves heap memory, connection time, and does not drain the battery of the peripheral by reading information from it that is not used by the program.

Because a retrieve descriptor by UUID does not exist in the stack (like it does for services and characteristics) the design is as follows:

1. If the descriptor is already in the vector of descriptors just return a reference to it
2. If no descriptors are retrieved yet for this characteristic, retrieve just one starting at the handle of the _characteristic_
3. If any descriptor has already been retrieved for this characteristic, retrieve just one resuming from the latest retrieved _descriptor_ in the vector
4. If the one descriptor retrieved has the UUID we are looking for, stop searching and return a reference to it
5. If not, and we are not at the last handle of the characteristic yet, increment the start handle by 1 and start over again from step 2

In this way the minimum number of descriptors is retrieved, but any (possibly unneeded) descriptor _before_ the one we are looking for is also retrieved.

The implementation is **not monkey proof**. If you call getDescriptor(... uuid ...) with a UUID that _does not exist_ in the characteristic all _characteristics_ and all _descriptors_ of the _service_ AFTER the characteristic for which getDescriptor() is called for are added in the descriptor vector _as descriptors_ for the characteristic. This is obviously wrong.

With PR #40, #56 and this PR (#57), after connecting to a client, it has no services, no characteristics and no descriptors. Every time a _new_ UUID is requested by getService(), getCharacteristic() or getDescriptor(), it is retrieved from the peripheral and 'remembered' for reuse.

Example:
```
#include <Arduino.h>
#include <string>

#include <NimBLEDevice.h>


void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  Serial.println("\n\nStarted");
  Serial.printf("Free heap before connection is %u\n", ESP.getFreeHeap());

  BLEDevice::init("ESP32");

  BLEClient *pClient = BLEDevice::createClient(false);

  BLEAddress address = BLEAddress("a4:c1:38:5d:ef:16");

  Serial.println("Connecting...");
  uint32_t startMillis = millis();
  pClient->connect(address);
  if(pClient->isConnected()) {
    uint32_t durationMillis = millis()- startMillis;
    Serial.printf("Connected, took %u ms\n", durationMillis);

    Serial.printf("Free heap after connection is %u\n", ESP.getFreeHeap());

    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    NimBLERemoteService *pService = pClient->getService(NimBLEUUID(0xebe0ccb0, 0x7a0a, 0x4b0c, 0x8a1a6ff2997da3a6));
    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    NimBLERemoteCharacteristic *pCharacteristic = pService->getCharacteristic(NimBLEUUID(0xebe0ccc1, 0x7a0a, 0x4b0c, 0x8a1a6ff2997da3a6));
    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    pCharacteristic->getDescriptor(NimBLEUUID(uint16_t(0x2901)));
    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    pCharacteristic->getDescriptor(NimBLEUUID(uint16_t(0x2803)));
    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    pClient->getService(NimBLEUUID(0x00010203, 0x0405, 0x0607, 0x08090a0b0c0d1912));
    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    pClient->getService(NimBLEUUID(uint16_t(0x180a)));
    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    pClient->disconnect();
  }
}

void loop() {
  // put your main code here, to run repeatedly:

}

```
Output:
```
Started
Free heap before connection is 291968
Connecting...
Connected, took 365 ms
Free heap after connection is 276048
Client:
peer address: a4:c1:38:5d:ef:16
Services:
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
Characteristic: uuid: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6, handle: 54 0x0036, props:  0x12
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
Characteristic: uuid: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6, handle: 54 0x0036, props:  0x12
Descriptor: uuid: 0x2901, handle: 55
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
Characteristic: uuid: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6, handle: 54 0x0036, props:  0x12
Descriptor: uuid: 0x2901, handle: 55
Descriptor: uuid: 0x2902, handle: 56
Descriptor: uuid: 0x2803, handle: 57
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
Characteristic: uuid: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6, handle: 54 0x0036, props:  0x12
Descriptor: uuid: 0x2901, handle: 55
Descriptor: uuid: 0x2902, handle: 56
Descriptor: uuid: 0x2803, handle: 57
Service: uuid: 00010203-0405-0607-0809-0a0b0c0d1912, start_handle: 29 0x001d, end_handle: 32 0x0020
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
Characteristic: uuid: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6, handle: 54 0x0036, props:  0x12
Descriptor: uuid: 0x2901, handle: 55
Descriptor: uuid: 0x2902, handle: 56
Descriptor: uuid: 0x2803, handle: 57
Service: uuid: 00010203-0405-0607-0809-0a0b0c0d1912, start_handle: 29 0x001d, end_handle: 32 0x0020
Service: uuid: 0x180a, start_handle: 12 0x000c, end_handle: 24 0x0018
------
```

As can be seen in the output getDescriptor(0x2901) retrieves just one descriptor, because it is the _first_ descriptor found. However getDescriptor(0x2803) retrieves **two** additional descriptors, because the requested descriptor with UUID 0x2803 is the _third_ descriptor found.

### CODE REVIEW

**Comment by h2zero** [comment]
Good attempt, but much of that is unnecessary, would be much better to just apply the uuid filter in the callback then stop the discovery when found.

**Comment by Jeroen88** [comment]
> just apply the uuid filter in the callback then stop the discovery when found

That was indeed my first attempt, but once you request descriptors between to handles the stack will send them, you can not stop discovery. That is the reason why I retrieve the descriptors one at a time.

**Comment by h2zero** [comment]
@Jeroen88, I poked at this a bit while at work. I pushed a new branch ` disc-indv-attributes `, that I think will do everything you're looking for. I have not tested as I'm still at work. Let me know what you think if you get a chance.

**Comment by Jeroen88** [comment]
@h2zero Thank you so much for putting effort in the non-auto discovery! I will have a look at it most likely tomorrow.

**Comment by Jeroen88** [comment]
@h2zero I took a quick look, I'll try it tomorrow. How should I get the behavior of not pre retrieving the full database?

**Comment by h2zero** [comment]
That code has been eliminated. No need to do anything but connect > get service > get characteristic > get descriptor.

**Comment by h2zero** [comment]
Well, good thing you didn't test it, got stuck on the semaphore ( kinda expected) fixed now though. Give it a shot if you can and let me know how it works for you.

**Comment by Jeroen88** [comment]
@h2zero I have done a few tests and the `disc-indv-attributes` branch works as expected. **This is really great!** Thank you very much! I can't wait to get it merged, do you already have a plan in mind?

> That code has been eliminated. 

I think the option to fully scan a device should be available again. This option is great for exploring all available services, characteristics and descriptors in an unknown device.

**Comment by Jeroen88** [comment]
I will close the PR's I made in this context, believing that you'll prefer your own code :laughing:

**Comment by h2zero** [comment]
Glad it’s to your satisfaction.

The option to get all has been added already as well. `NimBLEClient::discoverAttributes().`

**Comment by Jeroen88** [comment]
Do you think the changes in `disc-indv-attributes` will be merged soon? I **want** them!! :laughing:

**Comment by h2zero** [comment]
I will merge it soon, just made some adjustments last night and need to do a test compile with IDF (more strict compilation).

**Comment by Jeroen88** [comment]
Thnx, I am going to use it right after you merge!

**Comment by h2zero** [comment]
Done

**Pull request closed without merging**
