### PR TITLE
No auto services, includes PR #40

### PR DESCRIPTION
**Pull request by Jeroen88**
No automatic discovery of services. A service is retrieved by uuid one time (and remembered) when it is requested for the first time, like PR #40 already did for characteristics.

So after connection, a client has no services, no characteristics and no descriptors. After a `getService( ... uuid ...)` is called, only the service for that uuid is added (if found at the peripheral). After a `getCharacteristic (... uuid ...)` is called, only the characteristic for that uuid is added (also if found at the peripheral). 

In this way:
- connecting is much faster, because the pre retrieval takes time
- only heap memory for the services and characteristics requested is needed, saving a lot of heap
- less battery draining of the peripheral

One drawback, possibly to be solved: descriptors still to be added using the same mechanism. For now it is impossible to read or write a descriptor without pre retrieval.

Example:

```
#include <Arduino.h>
#include <string>

#include <NimBLEDevice.h>


void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  Serial.println("\n\nStarted");
  Serial.printf("Free heap before connection is %u\n", ESP.getFreeHeap());

  BLEDevice::init("ESP32");

  BLEClient *pClient = BLEDevice::createClient(false);

  BLEAddress address = BLEAddress("a4:c1:38:5d:ef:16");

  Serial.println("Connecting...");
  uint32_t startMillis = millis();
  pClient->connect(address);
  if(pClient->isConnected()) {
    uint32_t durationMillis = millis()- startMillis;
    Serial.printf("Connected, took %u ms\n", durationMillis);

    Serial.printf("Free heap after connection is %u\n", ESP.getFreeHeap());

    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    NimBLERemoteService *pService = pClient->getService(NimBLEUUID(0xebe0ccb0, 0x7a0a, 0x4b0c, 0x8a1a6ff2997da3a6));
    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    pService ->getCharacteristic(NimBLEUUID(0xebe0ccc1, 0x7a0a, 0x4b0c, 0x8a1a6ff2997da3a6));
    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    pClient->getService(NimBLEUUID(0x00010203, 0x0405, 0x0607, 0x08090a0b0c0d1912));
    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    pClient->getService(NimBLEUUID(uint16_t(0x180a)));
    Serial.println("Client:");
    Serial.printf("%s", pClient->toString().c_str());
    Serial.println("------");

    pClient->disconnect();
  }
}

void loop() {
  // put your main code here, to run repeatedly:

}

```

Output:
```
Started
Free heap before connection is 286976
Connecting...
Connected, took 1485 ms
Free heap after connection is 276048
Client:
peer address: a4:c1:38:5d:ef:16
Services:
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
Characteristic: uuid: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6, handle: 54 0x0036, props:  0x12
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
Characteristic: uuid: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6, handle: 54 0x0036, props:  0x12
Service: uuid: 00010203-0405-0607-0809-0a0b0c0d1912, start_handle: 29 0x001d, end_handle: 32 0x0020
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
Characteristic: uuid: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6, handle: 54 0x0036, props:  0x12
Service: uuid: 00010203-0405-0607-0809-0a0b0c0d1912, start_handle: 29 0x001d, end_handle: 32 0x0020
Service: uuid: 0x180a, start_handle: 12 0x000c, end_handle: 24 0x0018
------

```

### CODE REVIEW

**Comment by Jeroen88** [comment]
@h2zero did you see, 10k of heap is taken after connect. Any idea for what?

**Comment by h2zero** [comment]
>@h2zero did you see, 10k of heap is taken after connect. Any idea for what?

The NimBLE task automatically takes 4096 bytes when started, plus possibly some dynamic buffers. Then creating the device and client objects and probably a few bytes taken by the ble controller.

**Comment by Jeroen88** [comment]
@h2zero thnx!

**Comment by h2zero** [comment]
Just made a patch for this, only had an hour to play with it so it's incomplete and needs more work but it's working. Try it out on your end, you can see where I was going with it. At least it's a start to the descriptor problem.

[patch0.txt](https://github.com/h2zero/NimBLE-Arduino/files/4660581/patch0.txt)

**Comment by Jeroen88** [comment]
@h2zero The patch does not work as I expected. With the patch, once you call `getCharacteristic(... uuid ...)`, all descriptors of the characteristic are automatically retrieved and added to the descriptor vector of the characteristic. This is the output of the above example after applying your patch:

```
Started
Free heap before connection is 291968
Connecting...
Connected, took 259 ms
Free heap after connection is 276048
Client:
peer address: a4:c1:38:5d:ef:16
Services:
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
Characteristic: uuid: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6, handle: 54 0x0036, props:  0x12
Descriptor: uuid: 0x2901, handle: 55
Descriptor: uuid: 0x2902, handle: 56
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
Characteristic: uuid: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6, handle: 54 0x0036, props:  0x12
Descriptor: uuid: 0x2901, handle: 55
Descriptor: uuid: 0x2902, handle: 56
Service: uuid: 00010203-0405-0607-0809-0a0b0c0d1912, start_handle: 29 0x001d, end_handle: 32 0x0020
------
Client:
peer address: a4:c1:38:5d:ef:16
Services:
Service: uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6, start_handle: 33 0x0021, end_handle: 75 0x004b
Characteristic: uuid: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6, handle: 54 0x0036, props:  0x12
Descriptor: uuid: 0x2901, handle: 55
Descriptor: uuid: 0x2902, handle: 56
Service: uuid: 00010203-0405-0607-0809-0a0b0c0d1912, start_handle: 29 0x001d, end_handle: 32 0x0020
Service: uuid: 0x180a, start_handle: 12 0x000c, end_handle: 24 0x0018
------

```
As you can see, although getDescriptor(... uuid ...) was never called, the descriptors are there.

Also, although I am not a 100% sure, one descriptor is missing. It looks like characteristic ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6 has **three** descriptors:

```
Descriptor: uuid: 0x2901, handle: 55
Descriptor: uuid: 0x2902, handle: 56
Descriptor: uuid: 0x2803, handle: 57
```
The third one is missing in the output using your patch.

It took me quite some headache to solve it, but I think I succeeded. I will do a PR right now.

**Comment by h2zero** [comment]
This patch was for testing the characteristic end handle correctness, which does seem to work, I just threw it in the getCharactersic call to save time. 

There is no capability in the BLE core specification to retrieve only 1 descriptor, only services and characteristics can be requested by uuid, descriptors and a get all or none deal, unless the results are filtered after for our purposes. 

Also the 2803 “descriptor” you see there is the characteristic definition for the next characteristic in the database, that’s why the end handle is that point -1.

**Comment by Jeroen88** [comment]
> Also the 2803 “descriptor” you see there is the characteristic definition for the next characteristic in the database

Does that mean that if I find a 2803 descriptor I can stop searching because this descriptor and what is following belongs to the next characteristic? Would be great! If so I add that to PR #57

**Comment by Jeroen88** [comment]
Added the check for UUID is 0x2803. This indicates the next characteristic, so the end of the characteristic being searched is found. Searching must stop and the callback reports a return value of 1, indicating a 'not found'.

With this change:
- The 0x2803 "descriptor" is no more reported, since it is an indication for the next characteristic (thank you @h2zero)
- The function `getDescriptor(... uuid ...)` is monkey proof now. Requesting an non-existing UUID will still retrieve all descriptors associated with the characteristic, but no more than that. The non existing UUID is correctly reported as 'not found' by returning a `nullptr`.

**Comment by Jeroen88** [comment]
Closed because the ideas of this PR are developed in branch `disc-indv-attributes`.

**Pull request closed without merging**
