### PR TITLE
Fix crashing caused by calling time() in a critical section

### PR DESCRIPTION
**Pull request by doudar**
Fix for random notify crash in ISR context when  m_timestamp = time(nullptr); was called. 

@h2zero was the brains behind this, I just tested it for him and provided crash reports.

### CODE REVIEW

**Comment by h2zero** [comment]
Thanks for the PR!

There are a few other places that should have the same fix applied. If you'd like to do those and update this feel free to do so. Or I can fix them after.

**Comment by doudar** [comment]
I'm pretty new to pull requests, so I'd enjoy sifting through and finding them if you'll let me.

**Comment by h2zero** [comment]
Go for it! 

Just search through the files and find anywhere that `time()` is called within `portENTER_CRITICAL` and apply the same fix then push the changes to your master branch and they will update this PR.

**Comment by doudar** [comment]
After applying this in the 4 spots I found, it seems to be working so far but I did get one crash I've never seen shortly after the first startup. Backtrace doesn't seem helpful to me.

23 0 bd 0 0 0 0 0 0 <-- CPMC sent
Guru Meditation Error: Core  0 panic'ed (LoadStoreError). Exception was unhandled.
Core 0 register dump:
PC      : 0x4001742d  PS      : 0x00060f33  A0      : 0x8004a7b4  A1      : 0x3ffb5d60
A2      : 0x3ffb307c  A3      : 0x4002863e  A4      : 0x3ffb4934  A5      : 0x00000000
A6      : 0x3ffb8360  A7      : 0x40013fb8  A8      : 0x8008d694  A9      : 0x3ffb5d40
A10     : 0xffffffff  A11     : 0x00000064  A12     : 0x00000002  A13     : 0x00000001
A14     : 0x00060f23  A15     : 0x00000000  SAR     : 0x0000001d  EXCCAUSE: 0x00000003
EXCVADDR: 0x4002863e  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0xffffffff

ELF file SHA256: 0000000000000000000000000000000000000000000000000000000000000000

Backtrace: 0x4001742d:0x3ffb5d60 0x4004a7b1:0x3ffb5d80 0x401ab241:0x3ffb5da0 0x401a84b1:0x3ffb5dc0 0x400469b6:0x3ffb5e10 0x40019d11:0x3ffb5e40 0x40055b4d:0x3ffb5e60 0x401a2557:0x3ffb5e80 0x401a2a9d:0x3ffb5ea0 0x40093bf9:0x3ffb5ed0

Rebooting...


PC: 0x4001742d
EXCVADDR: 0x4002863e

Decoding stack results
0x40093bf9: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c line 143

**Comment by doudar** [comment]
And WiFi (loading a webpage hosted by the ESP32), stops the BLE processes from returning. I'll turn on NimBLE logging and see if I get anything useful.

**Comment by h2zero** [comment]
Lol yeah, that backtrace is pretty useless. I would try undoing each change one at a time until I found the problem one. Let me know.

**Comment by h2zero** [comment]
I did a quick search and can only find 3 instances of this, the fourth that you found could be the cause. Not sure where that is.

**Comment by doudar** [comment]
It was in NimBLEScan.cpp, but that was causing an issue. It didn't match your criteria, so that was the first one I removed. Solved the WiFi hang and I haven't seen that crash again since.  

`if(event->disc.length_data > 0) {
                advertisedDevice->parseAdvertisement(event->disc.data, event->disc.length_data);
            }
            advertisedDevice->m_timestamp = time(nullptr);

            if (pScan->m_pAdvertisedDeviceCallbacks) {
                if(pScan->m_wantDuplicates || !advertisedDevice->m_callbackSent) {`

**Comment by doudar** [comment]
I am currently having an issue with one of my characteristics not being updated. Trying to sort that out where that problem is coming from.

**Comment by h2zero** [comment]
That makes sense, only need to worry about the `portENTER_CRITICAL` areas that call `time()` inside them, everywhere else is fine as is. 

>I am currently having an issue with one of my characteristics not being updated. Trying to sort that out where that problem is coming from.

Sounds like more changes need to be undone?

**Comment by doudar** [comment]
I think that was a windows/zwift issue^^ I had moved my BLE adaptor. Seems to be working okay after a system restart. Continuing to poke it until I break something.

**Comment by h2zero** [comment]
Good work, poke on!

**Comment by doudar** [comment]
Thanks for letting me do that. 

If you wouldn't mind - why did changing it in NimBLEScann.cpp cause an issue? (I realize the fix wasn't needed there)

is `advertisedDevice->m_timestamp` not compatible with type time_t?

**Comment by h2zero** [comment]
No problem, thanks for saving me the time! 

My first thought is you might have added a`portENTER(EXIT)_CRITICAL` block there, but I didn't see what was done. 
If that was not the case, I'm really not sure why it would cause an issue. Something to test when I'm bored 😆 .

**Comment by doudar** [comment]
I had done:

`time_t t = time(nullptr);
advertisedDevice->m_timestamp = t;`

**Comment by h2zero** [comment]
PR looks good, if you don't mind could we change the title to "Fix crashing caused by calling time() in a critical section"? I'd just like to make the commit message clearer.

**Comment by doudar** [comment]
No issues - work your magic!

**Comment by doudar** [comment]
And from some short reading, it seems time() occasionally took too long to be in the critical section?

**Comment by h2zero** [comment]
>I had done:
time_t t = time(nullptr); advertisedDevice->m_timestamp = t;

Well that is interesting, could be some kind of timing issue going on there but that's quite the puzzle.
Would be hard to reproduce as your timing with wifi procedures at the same moment may have triggered it but I'll make a note to try this later.

**Comment by h2zero** [comment]
>And from some short reading, it seems time() occasionally took too long to be in the critical section?

Yes it should not have been in the section as it does quite a bit of processing and mutex locking which is what caused the problem. 
Critical sections should be quick flag flip sort of operations just like ISR's.

**Pull request merged**
