### PR TITLE
Map to vector v2 (this was PR #37)

### PR DESCRIPTION
**Pull request by Jeroen88**
Add `NimBLEAdvertisedDevice *getDevice(const NimBLEAddress &address)` to get a pointer to an advertised device by address.

This is useful for devices that send information in their service data. Now you can do:
```
NimBLEAdvertisedDevice *dev = pBLEScan->getResults().getDevice(NimBLEAddress("58:2d:34:39:22:58"));
if(dev != nullptr && dev->haveServiceData()) {
  const uint8_t * pData = (const uint8_t*)(dev->getServiceData().data());
  ... do something with the service data ...
}
```

This was PR #37, but since @h2zero merged master into this PR at May 15, 2020, I could not push my branch again. So I created a new branch by pulling from PR #37. So this branch **includes** the master merged by @h2zero. I am not aware if this leads to additional diffs from that master with PR #37 ...

### CODE REVIEW

**Comment by h2zero** [comment]
@Jeroen88 sorry about that, I thought you were done with the PR, I was fixing up conflicts. Will merge #37 soon.

**Comment by Jeroen88** [comment]
> sorry about that

No problem!

**Comment by Jeroen88** [comment]
@h2zero I just realized that the `getDevice()` using an index currently in `master` is **incorrect** on an index out-of-bounds! I think it will crash if no devices are found yet while still calling `getDevice()`, otherwise it will always return the first device discovered if the index is out-of-bounds.

**Comment by Jeroen88** [comment]
@h2zero I updated all my open PR's _except_ #42 to the latest master

**Pull request merged**
